/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
   
    java 
application 
}

repositories {
  
    mavenCentral()
    }


dependencies {
   
implementation("org.springframework.boot:spring-boot-starter-web:2.7.0") 
testImplementation("junit:junit:4.13.2")
}


application { 
mainClass.set("com.example.App")
}
